# Generated by Django 5.2.6 on 2025-10-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0002_refresh_collation_reindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceuserresourcepermission',
            name='target',
            field=models.CharField(db_index=True, max_length=128, verbose_name='知识库/应用id'),
        ),
    ]
