# Generated by Django 5.2.9 on 2025-12-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_application_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationversion',
            name='application_enable',
            field=models.BooleanField(default=False, verbose_name='应用是否启用'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='application_ids',
            field=models.JSONField(default=list, verbose_name='应用ID列表'),
        ),
    ]
